export const ROUND_DESCRIPTIONS = [
  {
    round: 1,
    scenarioHeading: 'Your company is facing a __liquidity crunch__.',
    scenarioBody: 'Cash reserves are running low and the business needs capital within weeks. You must decide how to raise money before operations are affected.',
    conceptName: 'Debt and Equity Financing',
    conceptDefinition: 'When a company needs money it can borrow from a bank and pay interest, or sell a share of itself to investors and give up some future profit.',
    analystQuote: 'Debt keeps your ownership intact, but every dollar you borrow costs you more than a dollar to repay.',
  },
  {
    round: 2,
    scenarioHeading: 'Investors want to see __growth__.',
    scenarioBody: 'The board is watching your numbers closely. Demonstrating that borrowed capital is being put to work efficiently is now critical.',
    conceptName: 'The True Cost of Borrowing',
    conceptDefinition: 'Every loan has a price — the interest you pay each month reduces the cash available to run and grow the business.',
    analystQuote: 'A loan is not free money — it is future revenue spent in advance, with a fee attached.',
  },
  {
    round: 3,
    scenarioHeading: 'It is time to __invest__ in the future.',
    scenarioBody: 'Three projects are competing for your capital. Each has a different return, risk level, and payback timeline.',
    conceptName: 'Evaluating an Investment',
    conceptDefinition: 'A good investment earns back more than it cost — but the timing of when the money comes back matters as much as the total amount.',
    analystQuote: 'The safest option is rarely the most valuable — calibrate risk to how much runway you have.',
  },
  {
    round: 4,
    scenarioHeading: 'A decision made today has a __long shadow__.',
    scenarioBody: 'The investment from round three is still maturing. Understand why a return that arrives in two years is worth less than the same return today.',
    conceptName: 'The Time Value of Money',
    conceptDefinition: 'One million dollars today is worth more than one million dollars in two years because today\'s money can be invested and grow in the meantime.',
    analystQuote: 'Patience is a virtue, but cash that sits idle is quietly losing value every day.',
  },
  {
    round: 5,
    scenarioHeading: 'Risk is __everywhere__. The question is your price.',
    scenarioBody: 'A threatening event is on the horizon and you can pay to be shielded from its impact. Decide whether the cost of protection is worth it.',
    conceptName: 'Risk Management and Protection',
    conceptDefinition: 'Companies often pay to protect themselves from bad events even when the cost seems high, because the alternative could permanently damage the business.',
    analystQuote: 'Insurance looks expensive right up until the moment you need it.',
  },
  {
    round: 6,
    scenarioHeading: 'This is your __final__ round.',
    scenarioBody: 'Every decision you have made since round one is now reflected in your company value. Make the last move count.',
    conceptName: 'Business Valuation',
    conceptDefinition: 'A company\'s value is not just what it owns today — it is the total of all the future profits it is expected to generate, discounted back to today\'s money.',
    analystQuote: 'Buyers do not pay for the past — they pay for what they believe the future looks like.',
  },
]
